name: 🐛 Bug Report
description: The provider does not work properly?
title: "BUG: "
labels:
  - bug
assignees:
  - siketyan
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: provider-version
    attributes:
      label: Provider Version
      description: What version of the provider are you using?
    validations:
      required: true
  - type: input
    id: tf-version
    attributes:
      label: Version
      description: What version of Terraform are you using?
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Operating system and its version, CPU architecture, etc.
    validations:
      required: true
  - type: textarea
    id: tf
    attributes:
      label: Terraform file
      description: Content of your terraform file(s). Remove any sensitive information if needed.
      render: terraform
  - type: textarea
    id: log
    attributes:
      label: Log output
      description: Copy and paste the log output on planning or applying.
      render: sh
